language: zh-Hans

banner:
  enable: true
  title:
    - Namida
    - 的
    - 博
    - 客
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

notice:
  enable: false
  content: 感谢您的访问！

# 可选 light | dark | auto | time
mode: light

cursor:
  enable: false
  default: https://cdn.yunyoujun.cn/css/md-cursors/pointer.cur
  pointer: https://cdn.yunyoujun.cn/css/md-cursors/link.cur
  text: https://cdn.yunyoujun.cn/css/md-cursors/text.cur

pages:

post_meta:
  item_text: true
  created_at: true
  updated_at: true
  categories: true
  tags: true

say:
  enable: false
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives/
      icon: ri:archive-line
    # - type: categories
    #   path: /categories/
    #   icon: ri:folder-2-line
    # - type: tags
    #   path: /tags/
    #   icon: ri:price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: ri:cloud-line
    #   count: 你猜
  # custom:
  #   title: 文档
  #   path: https://yun.yunyoujun.cn
  #   icon: ri:settings-line